// wrapTRIBOL_SIMPLE.h
// This file is generated by Shroud 0.12.1. Do not edit.

// Copyright (c) 2017-2023, Lawrence Livermore National Security, LLC and
// other Tribol Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (MIT)

/**
 * \file wrapTRIBOL_SIMPLE.h
 * \brief Shroud generated wrapper for TRIBOL_SIMPLE library
 */

// For C users and C++ implementation

#ifndef WRAPTRIBOL_SIMPLE_H
#define WRAPTRIBOL_SIMPLE_H

#include "typesTRIBOL_SIMPLE.h"
#ifndef __cplusplus
#include <stdbool.h>
#endif

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin C_declarations
// splicer end C_declarations

int TRIBOL_SIMPLE_initialize_0(const int dim);

int TRIBOL_SIMPLE_initialize_1(const int dim, bool init_slic);

int TRIBOL_SIMPLE_finalize_0(void);

int TRIBOL_SIMPLE_finalize_1(bool finalize_slic);

void TRIBOL_SIMPLE_simple_coupling_setup(const int dim, int contact_method, int mortar_numCells, int mortar_lengthNodalData, const int * mortar_connectivity, const double * mortar_x, const double * mortar_y, const double * mortar_z, int nonmortar_numCells, int nonmortar_lengthNodalData, const int * nonmortar_connectivity, const double * nonmortar_x, const double * nonmortar_y, const double * nonmortar_z, const double area_frac, double * mortar_gaps, double * mortar_pressures);

int TRIBOL_SIMPLE_update(double dt);

int TRIBOL_SIMPLE_get_simple_coupling_csr(int * * I, int * * J, double * * vals, int * n_offsets, int * n_nonzeros);

int TRIBOL_SIMPLE_get_simple_coupling_csr_bufferify(TRIBOL_SIMPLE_SHROUD_array *DI, TRIBOL_SIMPLE_SHROUD_array *DJ, TRIBOL_SIMPLE_SHROUD_array *Dvals, int * n_offsets, int * n_nonzeros);

#ifdef __cplusplus
}
#endif

#endif  // WRAPTRIBOL_SIMPLE_H
