# Set directory structures in places we can find easily
config:
  install_tree:
    root: $spack/..
    projections:
      all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
  misc_cache: $spack/../misc_cache
  test_stage: $spack/../test_stage
  build_stage::
  - $spack/../build_stage

# Regular TPLs do not need views
view: false

# Do not allow Spack to flip compiler families
concretizer:
  compiler_mixing: false

# Globally lock variants of third party libraries
packages:
  caliper:
    require:
    - spec: "~kokkos"
  conduit:
    require:
    - spec: "~shared~test~examples~utilities"
  hdf5:
    require:
    - spec: "~shared~mpi"
  mfem:
    require:
    - spec: "cxxstd=17"
  raja:
    require:
    - spec: "~shared~examples~exercises"
  umpire:
    require:
    - spec: "~shared~examples~werror"

  # Forward debug and shared variants to relevant tpls
  # NOTE: You can use build_type==Debug and ++shared to propagate variants from the smith spec instead, but it will affect external packages
  # as well and therefore leads to lower chances of concretization
  tribol:
    require:
    #######
    # Debug
    #######
    # Required dependencies
    - spec: "^axom build_type=Debug ^mfem+debug"
      when: "build_type=Debug"
    # Optional dependencies
    - spec: "^raja build_type=Debug"
      when: "+raja build_type=Debug"
    - spec: "^umpire build_type=Debug"
      when: "+umpire build_type=Debug"
    - spec: "^caliper build_type=Debug"
      when: "+caliper build_type=Debug"
    - spec: "^adiak build_type=Debug"
      when: "+adiak build_type=Debug"
    ########
    # Shared
    ########
    # Required dependencies
    - spec: "^axom+shared ^mfem+shared~static"
      when: "+shared"
    # Optional dependencies
    - spec: "^caliper+shared"
      when: "+shared+caliper"
    - spec: "^adiak+shared"
      when: "+shared+adiak"
    ########
    # Static
    ########
    # Required dependencies
    - spec: "^axom~shared ^mfem~shared+static"
      when: "~shared"
    # Optional dependencies
    - spec: "^caliper~shared"
      when: "~shared+caliper"
    - spec: "^adiak~shared"
      when: "~shared+adiak"
