# Copyright (c) 2017-2023, Lawrence Livermore National Security, LLC and
# other Tribol Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (MIT)

spack:
  compilers::
  - compiler:
      spec: clang@16.0.6
      paths:
        cc: /usr/lib/llvm-16/bin/clang
        cxx: /usr/lib/llvm-16/bin/clang++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: 
        cflags: -pthread
        cxxflags: -pthread
      operating_system: ubuntu24.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

  # Regular TPLs do not need views
  view: false

  packages:
    all:
      target: [ivybridge]
      compiler: [gcc]
      providers:
        blas: [openblas]
        lapack: [openblas]
        gl: [opengl]
        glu: [openglu]

    # Lock down versions of packages we depend on
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.71
        prefix: /usr
    automake:
      buildable: false
      externals:
      - spec: automake@1.16.5
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.8
        prefix: /
    cuda:
      buildable: false
      externals:
      - spec: cuda@12.8.0
        prefix: /usr/local/cuda
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.21
        prefix: /usr
    gmake:
      buildable: false
      externals:
      - spec: gmake@4.3
        prefix: /usr
    hwloc:
      buildable: false
      externals:
      - spec: hwloc@2.10.0
        prefix: /usr
    libevent:
      buildable: false
      externals:
      - spec: libevent@2.1.12
        prefix: /usr
    libtool:
      buildable: false
      externals:
      - spec: libtool@2.4.7
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.19
        prefix: /usr
    numactl:
      buildable: false
      externals:
      - spec: numactl@2.0.14
        prefix: /usr
    openssh:
      externals:
      - spec: openssh@9.6p1
        prefix: /usr
    openssl:
      externals:
      - spec: openssl@3.0.13
        prefix: /usr
    openblas:
      buildable: false
      externals:
      - spec: openblas@0.3.26
        prefix: /usr/lib/x86_64-linux-gnu/
    perl:
      buildable: false
      externals:
      - spec: perl@5.38.2
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@1.8.1
        prefix: /usr
    pmix:
      buildable: false
      externals:
      - spec: pmix@5.0.1
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.35
        prefix: /
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.5.5
        prefix: /usr

    # Lock in versions of Devtools
    cmake:
      buildable: false
      externals:
      - spec: cmake@3.28.3
        prefix: /usr
    doxygen:
      version: [1.8.17]
      buildable: false
      externals:
      - spec: doxygen@1.8.17
        prefix: /usr
    llvm:
      version: [14.0.6]
      buildable: false
      externals:
      - spec: llvm@14.0.6+clang
        prefix: /usr/lib/llvm-14
    python:
      version: [3.12.3]
      buildable: false
      externals:
      - spec: python@3.12.3
        prefix: /usr
    py-sphinx:
      version: [7.2.6]
      buildable: false
      externals:
      - spec: py-sphinx@7.2.6
        prefix: /usr

    # Globally lock version of third party libraries that work on this platform
    axom:
      require: "@0.9.0.2~shared~examples~fortran~lua~tools"
    camp:
      require: "@2024.07.0"
    conduit:
      variants: ~shared~test~examples~utilities
    raja:
      require: "@2024.07.0~shared~examples~exercises"
    umpire:
      require: "@2024.07.0~shared~examples"
