spack:
 # The "::" removes all found/known compilers from Spack except for these.
  compilers::
  - compiler:
      spec: clang@=20.1.2
      paths:
        cc: /opt/homebrew/opt/llvm/bin/clang
        cxx: /opt/homebrew/opt/llvm/bin/clang++
        f77: /opt/homebrew/bin/gfortran-14
        fc: /opt/homebrew/bin/gfortran-14
      flags: {}
      operating_system: sequoia
      target: aarch64
      modules: []
      environment: {}
      extra_rpaths:
      - /opt/homebrew/lib/gcc/14
  # add package specs to the `specs` list

  view: true
  concretizer:
    unify: true

  packages:
    all:
      compiler: [clang, gcc]
      providers:
        blas: [netlib-lapack]
        lapack: [netlib-lapack]
        mpi: [openmpi]

    mpi:
      buildable: false
    openmpi:
      buildable: false
      externals:
      - spec: openmpi@5.0.7
        prefix: /opt/homebrew
    
    # enzyme:
    #   version: [0.0.173]
    #   buildable: false
    #   externals:
    #   - spec: enzyme@0.0.173
    #     prefix: /opt/homebrew
    hdf5:
      version: [1.14.6]
      buildable: false
      externals:
      - spec: hdf5@1.14.6
        prefix: /opt/homebrew
    lua:
      version: [5.4.7]
      buildable: false
      externals:
      - spec: lua@5.4.7
        prefix: /opt/homebrew
    netlib-lapack:
      buildable: false
      externals:
      - spec: netlib-lapack@3.12.1
        prefix: /opt/homebrew/opt/lapack

    # Devtools
    # NOTE: cmake 4.0.0 is not compatible with metis and parmetis, stick with 3.31.6 for now
    cmake:
      version: [3.31.6]
      buildable: false
      externals:
      - spec: cmake@3.31.6
        prefix: /opt/homebrew
    doxygen:
      version: [1.13.2]
      buildable: false
      externals:
      - spec: doxygen@1.13.2
        prefix: /opt/homebrew
    llvm:
      version: [14.0.6, 20.1.2]
      buildable: false
      externals:
      - spec: llvm@14.0.6+clang
        prefix: /opt/homebrew/opt/llvm@14
      - spec: llvm@20.1.2+clang
        prefix: /opt/homebrew/opt/llvm
    python:
      version: [3.13.2]
      buildable: false
      externals:
      - spec: python@3.13.2
        prefix: /opt/homebrew
    py-sphinx:
      version: [8.2.3]
      buildable: false
      externals:
      - spec: py-sphinx@8.2.3
        prefix: /opt/homebrew

