compilers:
- compiler:
    environment:
      # Temporary workaround: Spack issue #18156
      set:
        SPACK_TARGET_ARGS: ""
    extra_rpaths: []
    flags:
      # Required as spack cannot recognize compiler-specific linker
      # flags in mixed toolchains
      ldlibs: -lgfortran
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang
      cxx: /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    spec: clang@10.0.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/xl/xl-2019.08.20/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2019.08.20/bin/xlC
      f77: /usr/tce/packages/xl/xl-2019.08.20/bin/xlf2003
      fc:  /usr/tce/packages/xl/xl-2019.08.20/bin/xlf2003
    spec: xl@16.1.1.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/xl/xl-2022.03.10-cuda-11.2.0/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2022.03.10-cuda-11.2.0/bin/xlC
      f77: /usr/tce/packages/xl/xl-2022.03.10-cuda-11.2.0/bin/xlf2003
      fc:  /usr/tce/packages/xl/xl-2022.03.10-cuda-11.2.0/bin/xlf2003
    spec: xl@16.1.1.12
    target: ppc64le