# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [netlib-lapack]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [netlib-lapack]
      mkl: [intel-mkl]
      mpe: [mpe2]
      # IBM Spectrum MPI is the only supported MPI 
      # library on LC's Sierra and CORAL EA systems.
      mpi: [spectrum-mpi]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
  python:
    variants: ~dbm
  py-numpy:
    variants: ~blas~lapack

  # LLNL blueos CUDA
  cuda:
    externals:
      - spec: cuda@11.2.0
        prefix: /usr/tce/packages/cuda/cuda-11.2.0
    buildable: false

  # LLNL blueos mpi
  mpi:
    buildable: false
  spectrum-mpi:
    externals:
      - spec: spectrum-mpi@release%clang@10.0.1
        prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-10.0.1-gcc-8.3.1
      - spec: spectrum-mpi@release%xl@16.1.1.1
        prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-xl-2019.08.20
      - spec: spectrum-mpi@release%xl@16.1.1.12
        prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-xl-2022.03.10

  netlib-lapack:
    externals:
      # This is the one that has the trailing underscores in name mangling, needed for MFEM compat
      - spec: netlib-lapack@3.9.0%clang@10.0.1
        prefix: /usr/tcetmp/packages/lapack/lapack-3.9.0-gcc-7.3.1/lib
      - spec: netlib-lapack@3.8.0%xl@16.1.1.1
        prefix: /usr/tcetmp/packages/lapack/lapack-3.8.0-xl-2019.08.20
      - spec: netlib-lapack@3.10.0%xl@16.1.1.12
        prefix: /usr/tcetmp/packages/lapack/lapack-3.10.0-xl-2022.03.10
    buildable: false

  # System level packages to not build
  autoconf:
    buildable: false 
    externals:
      - spec: autoconf@2.69
        prefix: /usr
  automake:
    buildable: false 
    externals:
      - spec: automake@1.13.4
        prefix: /usr
  binutils:
    buildable: false
    externals:
    - spec: binutils@2.27
      prefix: /usr
  bzip2:
    buildable: false
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  diffutils:
    buildable: false
    externals:
    - spec: diffutils@3.3
      prefix: /usr
  elfutils:
    buildable: false
    externals:
    - spec: elfutils@0.176
      prefix: /usr
  epoxy:
    buildable: false
    externals:
    - spec: epoxy@0.0.0
      prefix: /usr
  findutils:
    buildable: false
    externals:
    - spec: findutils@4.5.11
      prefix: /usr
  gettext:
    buildable: false 
    externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
  ghostscript:
    buildable: false
    externals:
    - spec: ghostscript@9.25
      prefix: /usr
  groff:
    buildable: false
    externals:
    - spec: groff@1.22.2
      prefix: /usr
  libtool:
    buildable: false
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
  libunwind:
    buildable: false
    externals:
    - spec: libunwind@8.0.1
      prefix: /usr
  m4:
    buildable: false
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  perl:
    buildable: false
    externals:
    - spec: perl@5.16.3
      prefix: /usr
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr
  readline:
    buildable: false
    externals:
    - spec: readline@6.2
      prefix: /usr
  tar:
    externals:
      - spec: tar@1.26
        prefix: /usr
    buildable: false

  # Lock in versions of Devtools
  cmake:
    version: [3.18.0]
    externals:
    - spec: cmake@3.18.0
      prefix: /usr/tce/packages/cmake/cmake-3.18.0
    buildable: false
  doxygen:
    version: [1.8.5]
    buildable: false
    externals:
    - spec: doxygen@1.8.5
      prefix: /usr
  llvm:
    version: [10.0.0]
    buildable: false
    externals:
    - spec: llvm@10.0.0
      prefix: /usr/tce/packages/clang/clang-10.0.0
  python:
    version: [3.8.2]
    externals:
      - spec: python@3.8.2
        prefix: /usr/tce/packages/python/python-3.8.2/
    buildable: false
  py-shroud:
    version: [0.12.1]
    buildable: false
    externals:
    - spec: py-shroud@0.12.1
      prefix: ~/.local
  py-sphinx:
    version: [4.5.0]
    buildable: false
    externals:
    - spec: py-sphinx@4.5.0
      prefix: ~/.local
