# Copyright (c) 2017-2023, Lawrence Livermore National Security, LLC and
# other Tribol Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (MIT)

spack:
  compilers::
  - compiler:
      spec: gcc@9.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: 
        cflags: -pthread
        cxxflags: -pthread
      operating_system: ubuntu20.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

  # Regular TPLs do not need views
  view: false

  packages:
    all:
      target: [ivybridge]
      compiler: [gcc]
      providers:
        mpi: [mpich]
        blas: [openblas]
        lapack: [openblas]

    # Lock down which MPI we are using
    mpi:
      buildable: false
    mpich:
      externals:
      - spec: mpich@3.3.2%gcc@9.4.0
        prefix: /usr

    # System level packages to not build
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    libyaml:
      buildable: false
      externals:
      - spec: libyaml@0.2.0
        prefix: /usr
    metis:
      buildable: false
      externals:
      - spec: metis@5.1.0
        prefix: /usr
    ncurses:
      buildable: false
      externals:
      - spec: ncurses@6.2
        prefix: /usr
    openblas:
      buildable: false
      externals:
      - spec: openblas@0.3.8
        prefix: /usr/lib/x86_64-linux-gnu
    parmetis:
      buildable: false
      externals:
      - spec: parmetis@4.0.3
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.1
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@8.0
        prefix: /
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.11
        prefix: /usr

    # Lock in versions of Devtools
    cmake:
      buildable: false
      externals:
      - spec: cmake@3.16.3
        prefix: /usr
    doxygen:
      version: [1.8.17]
      buildable: false
      externals:
      - spec: doxygen@1.8.17
        prefix: /usr
    llvm:
      version: [10.0.0]
      buildable: false
      externals:
      - spec: llvm@10.0.0
        prefix: /usr
    python:
      version: [3.8.10]
      buildable: false
      externals:
      - spec: python@3.8.10
        prefix: /usr
    py-shroud:
      version: [0.12.1]
      buildable: false
      externals:
      - spec: py-shroud@0.12.1
        prefix: ~/.local
    py-sphinx:
      version: [3.2.1]
      buildable: false
      externals:
      - spec: py-sphinx@3.2.1
        prefix: /usr

    # Globally lock version of third party libraries
    axom:
      require: "@0.8.1.0~examples~fortran~lua~tools~openmp~hdf5"
    camp:
      require: "@2023.06.0"
    conduit:
      require: "@0.8.8~shared~test~examples~utilities~hdf5"
    hypre:
      version: [2.24.0]
    raja:
      require: "@2023.06.0~shared~examples~exercises~openmp"
    umpire:
      require: "@2023.06.0~shared~examples~openmp"
